### PR TITLE
Add pydeck example using TerrainLayer

### LINKED ISSUE #4531: TerrainLayer binding in pydeck
#### Target Use case
 I want to be able to use the TerrainLayer in pydeck. It is not listed under the pydeck examples, so I guess it is not implemented yet?

#### Proposed feature
Sample code snippet of how it probably would be implemented:
```
import pydeck as pdk

ELEVATION_LAYER_DATA = 'https://raw.githubusercontent.com/uber-common/deck.gl-data/master/website/terrain.png'
TEXTURE = 'https://raw.githubusercontent.com/uber-common/deck.gl-data/master/website/terrain-mask.png'

layer = pdk.Layer(
        "TerrainLayer",
        data=ELEVATION_LAYER_DATA,
        elevationDecoder={
                'rScaler': 2,
                'gScaler': 0,
                'bScaler': 0,
                'offset': 0
                },
        texture=TEXTURE,
        bounds=[-122.5233, 37.6493, -122.3566, 37.8159]
        )

view_state = pdk.ViewState(latitude=37.7749295, longitude=-122.4194155, zoom=11, bearing=0, pitch=45)

# Render
r = pdk.Deck(layers=[layer], initial_view_state=view_state)
r.to_html("terrain_layer.html", notebook_display=False)
```
This sample was created following the style of the other pydeck examples and the deck.gl TerrainLayer example.

### PR DESCRIPTION
**Pull request by kylebarron**
#### Change List

- Adds example of using the `TerrainLayer` with pydeck

Closes #4531

### CODE REVIEW

**Comment by kylebarron** [comment]
Oh this is broken because I didn't realize Python 3.5 is supported, so I can't use f-strings syntax.

**Comment by ajduberstein** [comment]
Screenshot of the example would be great so we all know what it's supposed to look like! Otherwise, good to go.

**Comment by kylebarron** [comment]
It's the same example as the JS terrain layer example. Adding it to the website is a PR to pydeck.gl's docs, right? So I should submit a PR there adding it to the website?
image

**Comment by ajduberstein** [comment]
Failure will disappear if you rebase (it's my fault)

I'll add it to the docs and generate the thumbnail–right now you have to modify a few files in the docs/ folder to add it and I haven't recorded that process.

**Pull request merged**
