### PR TITLE
Configure search on website

### PR DESCRIPTION
**Pull request by Pessimistress**
For #7635 

#### Change List
- Add search config (indexed by [Algolia DocSearch](https://docsearch.algolia.com/))

### CODE REVIEW

**Review by ibgreen — APPROVED** [review]
Did we consider / compare with https://github.com/cmfcmf/docusaurus-search-local ? 

Nice to avoid another API key, unless experience is significantly better.

**Comment by ibgreen** [comment]
Or maybe that plugin is doing the same thing?

**Comment by Pessimistress** [comment]
I would like to avoid having to load the entire index on the client side. Local search is probably sufficient for the smaller libraries.

**Review by chrisgervang — APPROVED** [review]
Amazing how little config is required. Their free tier is generous from what I here - is that what we can use?

**Comment by Pessimistress** [comment]
Yes it's free for open source projects.

**Pull request merged**
