### PR TITLE
TerrainExtension (3/3)

### PR DESCRIPTION
**Pull request by Pessimistress**
For #7195

#### Change List
- Unit tests
- Render tests
- Increased render test timeout to 10s

### CODE REVIEW

**Comment by Pessimistress** [comment]
Raster tiles are checked into `test/data` following what we do with the MVTLayer render tests. CI seems to have really bad network bandwidth and is unable to load tiles from a remote server before timeout. We may be able to host them in deck.gl-data and pull them in with submodule or something, but I need to look into that.

**Comment by ibgreen** [comment]
> Raster tiles are checked into `test/data` following what we do with the MVTLayer render tests. CI seems to have really bad network bandwidth and is unable to load tiles from a remote server before timeout. We may be able to host them in deck.gl-data and pull them in with submodule or something, but I need to look into that.

My understanding was that openstreetmap data has a contagious license and we should try hard to avoid having any OSM data in the same repos as other data or code.

So yes, It might be worth setting up a small deck.gl-data-osm repo and use git submodule in yarn bootstrap.

**Review by ibgreen — APPROVED** [review]
just cleanup and test cases...

**Comment by ibgreen** [comment]
> Increased render test timeout to 10s

I have noticed that the render tests already do take a lot of time. I'd be curious to understand what drives that.

**Pull request merged**
