### PR TITLE
fixed MapboxOverlay props typing

### PR DESCRIPTION
**Pull request by YonatanHanan**

### CODE REVIEW

**Review by YonatanHanan — COMMENTED** [review]
Hi,

I fixed this little typing :)

**Comment by felixpalmer** [comment]
You've reformated the whole file. Please use the prettier config or run `yarn lint`

**Comment by Pessimistress** [comment]
What is the reason for this change? `interleaved` is only available in the constructor, and not in `setProps`.

**Comment by YonatanHanan** [comment]
> What is the reason for this change? `interleaved` is only available in the constructor, and not in `setProps`.

yes, but when you use this component in react you have to copy the `interleaved` property as if it is part of the props.
this is my code:
```TS
import { useControl } from 'react-map-gl';
import { MapboxOverlay } from '@deck.gl/mapbox/typed';
import type { MapboxOverlayProps } from '@deck.gl/mapbox/typed';

type MBDeckGLOverlayProps = MapboxOverlayProps & {
    interleaved?: boolean;
};

export const MBDeckGLOverlay = (props: MBDeckGLOverlayProps) => {
    const overlay = useControl<MapboxOverlay>(() => new MapboxOverlay(props));
    overlay.setProps(props);
    return null;
};
```

instead of 
```TS
import { useControl } from 'react-map-gl';
import { MapboxOverlay } from '@deck.gl/mapbox/typed';
import type { MapboxOverlayProps } from '@deck.gl/mapbox/typed';

export const MBDeckGLOverlay = (props: MBDeckGLOverlayProps) => {
    const overlay = useControl<MapboxOverlay>(() => new MapboxOverlay(props));
    overlay.setProps(props);
    return null;
};
```

**Review by Pessimistress — APPROVED** [review]

**Pull request merged**
