### PR TITLE
OrthographicView supports independent x/y zoom levels

### PR DESCRIPTION
**Pull request by Pessimistress**
#### Background

For the charting use case

deck gl-orthographic-controller

#### Change List
- `OrthographicViewport` accepts `zoom` as either a number (uniform zoom) or an array (independent zoom)
- `OrthographicController` new option `zoomAxis`
- Documentation
- Test

### CODE REVIEW

**Review by kylebarron — APPROVED** [review]

**Comment by felixpalmer** [comment]
You need to supply an 2D array to the `zoom` prop in the `viewState`: https://deck.gl/docs/api-reference/core/orthographic-view#view-state. You then update a the `viewState.zoom` with the correct values based on user input

**Comment by cornhundred** [comment]
Thanks @felixpalmer. I'm trying this [here](https://observablehq.com/d/358846a94ba6417b ):

```
deckgl = {
  return new deck.DeckGL({
    container,
    views: new deck.OrthographicView({controller: true}),
    initialViewState: {target: [0, 0, 0], zoom: [0, 0]},
    onViewStateChange: ({viewState}) => {
      viewState.zoom = [viewState.zoom[0], 0]
      return viewState
    }
  });
}
```
as a way of trying to limit the zooming to the X axis only and behaves as I would expect with two exceptions: 

1. The Y zooming seems to be dependent on the position of the cursor in the visualization (Y zooming does not occur if the cursor is kept in the middle of the visualization, but otherwise causes the points to 'zoom' up or down depending on whether the cursor is above or below the middle of the visual respectively)
2. The points do not increase in width as I would expect as I zoom in.

I'll read the documentation and see if I can figure out what is happening.

**Comment by Pessimistress** [comment]
@cornhundred You need to set [zoomAxis](https://deck.gl/docs/api-reference/core/orthographic-controller#options) of the controller.

**Comment by cornhundred** [comment]
Thanks @Pessimistress I'll start a discussion :)

**Pull request merged**
