### PR TITLE
fix(extensions): DataFilterExtension handling of filterSoftRange

### LINKED ISSUE #8774: [Bug] Filter extension soft range unexpected behavior
### Description

When using the filter extension, using a soft range that matches the filter range causes the filter to become start exclusive (it will filter out any values that match the minimum filter value.  The use case where this becomes an issue is where you only want to use soft filtering on one of the channels.  For example, if I have one attribute that I would like to apply soft filtering on, and a second attribute that I want to perform exact filtering on.  if I have a feature with a filter value of 3  in the exact channel and a filter of 3-5 and a soft filter of 3-5, the feature will not be visible.

### Expected Behavior

I would expect the soft filter to do nothing if the minimum or maximum value matches the minimum or maximum value of the base filter range.

### Steps to Reproduce

I have created a codepen that reproduces this behavior:
https://codepen.io/jdgarrett/pen/wvZjqLe
In this codepen, there should be a single feature that is visible because it lies within the first channel soft range and matches the second channel filter exactly.  There are comments in the codepen that explains in a bit more detail.

After digging into the code, this appears to be happening due to a divide by zero in the smoothstep function.  I would recommend doing a regular filter check for min/max if the smooth filter value matches the filter value.

### Environment

- Framework version: deck.gl@8.9.0
- Browser: Chrome 123.0
- OS: Windows

### Logs

_No response_

### PR DESCRIPTION
**Pull request by Pessimistress**
Closes #8774

#### Change List
- When `filterSoftRange` is truncated by `filterRange` fallback to use hard edge

### CODE REVIEW

**Review by ibgreen — APPROVED** [review]
A doc change warranted, or this is just an edge case?
Do we have a test harness?

**Review by felixpalmer — APPROVED** [review]

**Review by felixpalmer — COMMENTED** [review]
I wonder if it would be more efficient to keep the old shader and instead clip the value of the soft range in JS so it could never be in the wrong range

**Comment by Pessimistress** [comment]
@Ibgreen no doc change required, this is a bug fix

@felixpalmer the issue here is when filter_min equals filter_softMin we still cannot use smoothstep.

**Comment by felixpalmer** [comment]
@Pessimistress I was suggesting we avoid `filter_min === filter_softMin` by clamping `filter_softMin` to `filter_min + epsilon` in JavaScript

**Comment by Pessimistress** [comment]
If you look at the original issue, they are using filter_min == filter_softMin == filter_softMax == filter_max. It would not work with any modification.
And that's not even getting into how to determine epsilon for an arbitrary float32...

**Pull request merged**
