### PR TITLE
Abort Ongoing Tile Requests When New Tileset is Created

### PR DESCRIPTION
**Pull request by ilan-gold**
For #5297.  Adds a `finalize` function to the `Tileset2D` to handle aborting the ongoing tile requests when a new `Tileset2D` is about to be made by the layer.

I could add a test with `setTimeout` or something to guarantee tiles can actually be aborted but not sure that it's really a "unit test" at that point.  Also, I don't think I need to do anything to the visibility of the tiles since the previous (i.e the one having `finalize` called) `Tileset2D`'s tiles are all abandoned by the next render anyway (might have that wrong).

#### Background
Rapid changes on `updateTriggers` to the `TileLayer` can leave tile requests hanging, slowing down the application.  This PR adds the ability to abort ongoing requests when `updateTriggers` are triggered.

#### Change List
- Add a `finalize` function to `Tileset2D` for aborting ongoing tile requests.
- Changed the state variable from `tiles` to `tileset` in `initializeState` because `tiles` was removed some time ago.  I can remove this though, just noticed it.

### CODE REVIEW

**Comment by chrisgervang** [comment]
Hey! This looks good. I pulled it down yesterday and started to think about how we might add a test to cover it. I was thinking we could load a couple tiles, some loaded, some pending, then finalize and check the cache to look as expected.


Do you have an ideas for how you'd test it?

**Review by Pessimistress — APPROVED** [review]

**Review by chrisgervang — APPROVED** [review]

**Comment by ilan-gold** [comment]
I tried adding a test using `sleep` @chrisgervang and pushed the branch.  Let me know how that looks.

**Comment by ilan-gold** [comment]
@chrisgervang  I just realized we probably want to test the layer as well.  I will add that as well.

**Comment by chrisgervang** [comment]
Sounds good. I've written a second test for tileset-2d to cover a partial load, and a reload. Check it out here https://github.com/ilan-gold/deck.gl/compare/abort_tile_requests_on_update...visgl:chr/abort_tile_requests_on_update

**Comment by ilan-gold** [comment]
@chrisgervang I'm realizing that because the old `Tileset2D` is discarded, there may not be any way to test this on the layer i.e we can't access the old `layer.state.tileset` to check if tiles have been aborted.

**Review by kylebarron — APPROVED** [review]

**Comment by Pessimistress** [comment]
@ilan-gold You can query the tileset right after the initial update and hold on to the tile instances.

**Comment by ilan-gold** [comment]
@Pessimistress just saw this but had the same thought. Will do.

**Pull request merged**
