### PR TITLE
Normalize h3 cluster polygons longitudes

### PR DESCRIPTION
**Pull request by 4nthonylin**
For #8009 

#### Background
Normalize the longitudes of the h3 multi polygon in H3ClusterLayer. Note was having issues with tests unrelated with what I was touching so I am relying on CI for the tests, made a separate issue 8008
#### Change List
- Move some functions in h3-hexagon-layer into `h3_utils.ts`
- Update some of the interface to leverage `CoordPair`
- Normalize geo polygon rings in H3ClusterLayer

#### Before
image

#### After
image

### CODE REVIEW

**Comment by Pessimistress** [comment]
Thank you!

Do you mind adding a test case to https://github.com/visgl/deck.gl/blob/master/test/render/test-cases/h3-layers.js ?

**Comment by Pessimistress** [comment]
Imports need to be updated in `test/modules/geo-layers/h3-layers.spec.js`

**Comment by 4nthonylin** [comment]
Updated imports and added a new test case for H3ClusterLayer#antimeridian behavior.

**Review by Pessimistress — APPROVED** [review]
Thank you!

**Comment by 4nthonylin** [comment]
When this merges. Any chance we can get a new alpha release on top of 8.10?

**Pull request merged**
