### PR TITLE
Improve PointCloudLayer perf

### PR DESCRIPTION
**Pull request by Pessimistress**
Cuts vertex calculation by 2/3 by using `GL.POINTS` and `gl_PointCoord`.
There should not be any noticeable change to the visual outcome.

#### Change List
- Use `GL.POINTS` to draw point clouds

### CODE REVIEW

**Comment by ibgreen** [comment]
When I have used points in the past I got quite ugly results. Square points etc. It also seemed somewhat platform dependent though that might be hand wavy recollections. 

Ultimately I'd think the rasterizer is limiting perf, not the vertex stage. Would love to see performance numbers before making changes like this... @igorDykhta you were collecting performance on deck.gl rendering were you using any special tricks?

**Comment by igorDykhta** [comment]
@ibgreen gl queries before and after draw call of interest + force redraw to get the consistent average time. Not sure whether it is possible to get only vertex shader stats in WebGL(?). The easiest way is to just output solid color without any additional logic, and then benchmark the vs.

**Comment by Pessimistress** [comment]
Ok, `deck.metrics` show average GPU time per frame as 11.56ms, while master is 10.37ms (Chrome + OSX).

**Comment by ibgreen** [comment]
> Ok, deck.metrics show average GPU time per frame as 11.56ms, while master is 10.37ms 

That doesn't sound like an improvement?

Should we make the ability to draw with POINTS an option? I.e. we could support either points or triangles. 

Note that there are other implications, e.g. bias (aka polygonOffset) does not apply to POINTS.

**Comment by ibgreen** [comment]
BTW, thanks for trying this! This one didn't work out but I am sure we are leaving performance on the table and we need to experiment with our shaders.

**Pull request closed without merging**
