### PR TITLE
Fix GPUAggregator on M chips

### PR DESCRIPTION
**Pull request by Pessimistress**
For https://github.com/visgl/deck.gl/pull/8887#discussion_r1738284310

Tested on M2. Thanks @felixpalmer for the insight.

#### Change List
- Avoid interpolating NaNs

### CODE REVIEW

**Review by ibgreen — APPROVED** [review]
Great to finally see a fix!  I added MacOS if statements around some of the test cases in [`webgl-aggregator-spec.ts`](https://github.com/search?q=repo%3Avisgl%2Fdeck.gl%20device.info.gpu%20!%3D%3D%20%27apple%27&type=code), you might want to remove those.

----
Thoughts:

Since I haven't dug into the problem, several questions come to mind. 
- Why do the 3 vertices have different values (leading to interpolation issues) in the first place ? 
- Because AFAIK, using `flat` basically means just pick the value from the first vertex and ignore the other two...
- If the other two weren't needed, couldn't we just have populated them with the right values instead?
- Is this a solution we expect to apply in more places?

**Comment by Pessimistress** [comment]
There was never interpolation involved. This pass is drawing points geometry.

**Comment by ibgreen** [comment]
> There was never interpolation involved. This pass is drawing points geometry.

Then why does disabling interpolation (i.e. using `flat` even make a difference? It affects some edge case around NaN handling?

**Comment by Pessimistress** [comment]
It was not an improperly written shader to begin with, just that it was executed in an unexpected way by the M GPU. Adding an explicit `flat` seems to prompt it to run correctly.

**Comment by ibgreen** [comment]
OK sure. I did see that there was a linked discussion about shaders not being happy with NaNs. NaNs are notoriously unreliable. 

My thinking is basically that if the "undefined" behavior of NaNs is really the root cause, might we want to consider avoiding NaNs instead of adding "black magic" GLSL qualifiers.

To be clear, I have not objections to landing this, just trying to see if we can deepen our understanding of the problem.

**Review by felixpalmer — APPROVED** [review]
I know it is the 4.5 spec, not 3.0 but I found this note on [page 49](https://registry.khronos.org/OpenGL/specs/gl/GLSLangSpec.4.50.pdf):

> Fragment shader inputs that are, or contain, signed or unsigned integers, integer vectors, or any double-
precision floating-point type must be qualified with the interpolation qualifier flat.

Perhaps this is what is happening under the covers, the precision loss is degrading the `nan` value.

At any rate, happy to report the fix works on M3 also

**Comment by ibgreen** [comment]
> I found this note on [page 49](https://registry.khronos.org/OpenGL/specs/gl/GLSLangSpec.4.50.pdf):

Interesting. Sounds like best practice to add `flat` whenever we use fragment shaders for "pure calculations" then.

**Pull request merged**
