### PR TITLE
Bump loaders to 3.1.3

### PR DESCRIPTION
**Pull request by felixpalmer**

### CODE REVIEW

**Review by alasarr — APPROVED** [review]

**Review by ibgreen — APPROVED** [review]

**Comment by alasarr** [comment]
ey! I've seen an issue here, the CI never finishes and I get the following error in the browser when I try to start an example:

```
make-node-stream.ts:17 Uncaught TypeError: Class extends value undefined is not a constructor or null
    at Module.../../../../node_modules/@loaders.gl/core/dist/esm/iterators/make-stream/make-node-stream.js (make-node-stream.ts:17)
    at __webpack_require__ (bootstrap:789)
    at fn (bootstrap:100)
    at Module.../../../../node_modules/@loaders.gl/core/dist/esm/iterators/make-stream/make-stream.js (make-stream.ts:5)
    at __webpack_require__ (bootstrap:789)
    at fn (bootstrap:100)
    at Module.../../../../node_modules/@loaders.gl/core/dist/esm/index.js (index.ts:2)
    at __webpack_require__ (bootstrap:789)
    at fn (bootstrap:100)
    at Module.../../../../modules/core/src/lib/init.js (init.js:1)
```

**Comment by ibgreen** [comment]
Hmm, that might be related to a fix that was added for improving loaders.gl compatibility with vite and rollup. Maybe it is instead causing issues on webpack?

**Comment by alasarr** [comment]
I think so, are you referring to [this change](https://github.com/visgl/loaders.gl/blob/3.1-release/modules/core/src/iterators/make-stream/node-stream-polyfill.ts), right?

**Comment by ibgreen** [comment]
Yes. I suggest we revert that file (not the whole commit) and republish 3.1.2.

**Comment by felixpalmer** [comment]
> Yes. I suggest we revert that file (not the whole commit) and republish 3.1.2.

Sounds good to me. I'm also seeing that issue

**Comment by felixpalmer** [comment]
So, unfortunately this fix hasn't worked. It appeared OK locally, but I guess I'm misunderstanding something about how the packaging works. @ibgreen I saw you made https://github.com/visgl/loaders.gl/pull/2026 - is it correct that this will supersede the unsuccessful fix in https://github.com/visgl/loaders.gl/pull/2023 ?

**Comment by ibgreen** [comment]
> I saw you made visgl/loaders.gl#2026 - is it correct that this will supersede the unsuccessful fix in visgl/loaders.gl#2023 ?

It could, if we can make it work. CI is currently failing, will need to debug more.

**Comment by jessekrubin** [comment]
@ibgreen for the record I am getting a similar issue with vite/rollup with loaders 3.1.2

**Comment by ibgreen** [comment]
@felixpalmer Bumped to 3.1.3, CI passes now

**Comment by felixpalmer** [comment]
@ibgreen great thank you for a quick fix on this

**Pull request merged**
