### PR TITLE
chore(mapbox) use maplibre v3 instead of mapbox v1

### PR DESCRIPTION
**Pull request by chrisgervang**
For #8549

Note: maplibre v4 fails in our example due to a CORS issue, likely introduced with https://github.com/maplibre/maplibre-gl-js/pull/3233. Needs more investigation.

#### Change List
- use maplibre v3 instead of mapbox v1 in pure js example

### CODE REVIEW

**Review by cgalvan — APPROVED** [review]

**Review by felixpalmer — APPROVED** [review]

**Comment by Pessimistress** [comment]
There is a strong pushback from the maplibre community against using the "mapbox" brand name with their library for branding and legal reasons. For example, they would like us to publish a new submodule `@deck.gl/maplibre` with `MaplibreOverlay` (maybe not at this time), and have get-started boiler-plate examples named "maplibre" (we probably should).

I know this example is named after the submodule, but better not mix the two unless we have to.

**Comment by chrisgervang** [comment]
I think that's a good direction too given they'll only diverge overtime. Maybe the new module could be added to 9.1 roadmap? In the meantime, I can rename folders and library references to maplibre.

**Comment by Pessimistress** [comment]
> In the meantime, I can rename folders and library references to maplibre.

To be clear I did not advocate for "rename". We should not use the names "Mapbox" and "Maplibre" interchangeably. It's now equally confusing for the users of both libraries. We need separate doc pages and examples for both.

**Comment by HarelM** [comment]
@chrisgervang which version 4 of maplibre did you use?
Is it possible that this issue was fixed in the latest version?
See the following issue:
https://github.com/maplibre/maplibre-gl-js/issues/3680
In any case, if you are experiencing issues with maplibre v4 I would like to know as this version is new and there were a lot of refactoring there. I would be surprised if we introduced CORS issues, but anything is possible :-)

**Comment by chrisgervang** [comment]
Thanks @HarelM, I saw that issue too but it doesn't seem related. I've opened #8551 to figure this out

**Pull request merged**
