### PR TITLE
Set per-pass uniforms when postprocessing

### PR DESCRIPTION
**Pull request by felixpalmer**
#### Background

`ShaderPass` can set uniforms per pass, for example the `triangleBlur` changes the direction of the blur for x to y: https://github.com/visgl/luma.gl/blob/050f4e7ac58a3e1117d5ef2da9e1ecb8978aceb3/modules/shadertools/src/modules/postprocessing/image-blur-filters/triangleblur.ts#L77-L78

deck.gl is not setting these when rendering, causing many of the effects to render incorrectly, for example the triangle blur, renders twice in the x direction and never in the y direction.

### Incorrect (current)
Screenshot 2024-04-17 at 17 09 08

### Correct (fixed)
Screenshot 2024-04-17 at 17 09 28

Note that to test it is necessary to override `triangleBlur.uniformPropTypes.delta.private = false;`, as [luma is ignoring all private props](https://github.com/visgl/luma.gl/blob/050f4e7ac58a3e1117d5ef2da9e1ecb8978aceb3/modules/shadertools/src/lib/shader-module/shader-module-instance.ts#L155) (should be also fixed)

#### Change List
- Merge per-pass uniforms into `moduleSettings` when rendering post process pass

### CODE REVIEW

**Comment by Pessimistress** [comment]
Isn't this a luma bug? Module settings should not be required to list every uniform except the ones the user sets explicitly?

**Comment by ibgreen** [comment]
I am uncertain, I seem to recall that deck wrote its own ShaderPass handling instead of using the one in luma.gl, and then the shaderpass logic in luma.gl was stripped out by a maintainer who wanted to avoid keeping unused code. 

Happy to make a PR in luma if it is more clear where this is failing.

**Comment by felixpalmer** [comment]
@Pessimistress `PostProcessEffect` creates a separate `ScreenPass` for each of the passes in `ShaderPass.passes`. When it [iterates over them](https://github.com/visgl/deck.gl/blob/88271773c631901c7dbe43737416f3ab660ba904/modules/core/src/effects/post-process-effect.ts#L48) it doesn't pass any context to luma (e.g. the pass index) to let it know which pass is being rendered. Instead of the fix proposed in this PR, we could add `ShaderPassData` to module settings then rely on the `getUniforms` function to perform the merge instead

Note that the original design of the of the `ShaderPass` is a ["shader module with additional information on how to run"](https://github.com/visgl/luma.gl/blob/050f4e7ac58a3e1117d5ef2da9e1ecb8978aceb3/modules/shadertools/src/lib/shader-module/shader-pass.ts), so I don't think having deck merge in the per-pass uniforms is wrong. It is generating the fragment shader based on the values of `ShaderPassData.filter` and `ShaderPassData.sampler` after all

@ibgreen it would be useful to have a minimal example in luma for the `triangleBlur` effect, as currently the only way (that I'm aware) of running the post-processing effects is via deck

**Comment by ibgreen** [comment]
> @ibgreen it would be useful to have a minimal example in luma for the triangleBlur effect, as currently the only way (that I'm aware) of running the post-processing effects is via deck

Yes luma.gl used to have a great example including all the post-processing effects, but it was derived from code written in jquery UI and required maintaining special build steps - so it was removed at some point by overloaded maintainers. I've made some half-hearted attempts to port that example but it does require a bit of work. Perhaps if someone wished to pair on it...

**Review by ibgreen — APPROVED** [review]

**Pull request merged**
