### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by jamesEmerson112**
A slight adjustment for compatibility among the packages

For # 7687

#### Background
The following packages request esri-loader to be on version 2.14.0 instead of 3.3.0
"@arcgis/core": "^4.21.0",
"@esri/react-arcgis": "^5.1.0"

#### Change List
- N/A

### CODE REVIEW

**Comment by Pessimistress** [comment]
Don't you need to update https://github.com/visgl/deck.gl/blob/master/modules/arcgis/package.json as well?

**Comment by jamesEmerson112** [comment]
> Don't you need to update https://github.com/visgl/deck.gl/blob/master/modules/arcgis/package.json as well?

Thank you for making the time! 

Regarding the attached link, I am not knowledgeable enough to make a comment. 

With that being said, this PR is particularly for https://github.com/visgl/deck.gl/blob/master/examples/get-started/react/arcgis/package.json specifically.

Once I am knowledgeable enough, I am happy to circle back to https://github.com/visgl/deck.gl/blob/master/modules/arcgis/package.json

**Comment by Pessimistress** [comment]
`@arcgis/core` does not require `esri-loader`: https://unpkg.com/browse/@arcgis/core@4.26.1/package.json
`@deck.gl/arcgis` require `esri-loader` to be v3, which is still the latest.
`@esri/react-arcgis` locks `esri-loader` to 2.14.0. I don't know why they do it but you should probably report it to that package's maintainers.

My suggestions: 
- There is no need to add `@deck.gl/arcgis` to package.json, it's already a dependency of `deck.gl`.
- If you remove `esri-loader` from package.json you should not see any errors. You'll end up with both versions of `esri-loader` as sub dependencies but that should be ok.

**Comment by jamesEmerson112** [comment]
Much appreciated!


Somehow, `@deck.gl/arcgis` does not show up after npm install (`npm@9.5.1`, latest version) in the examples. Perhaps, it is something on my end? 
@deck.gl/arcgis does not show up in the "arcgis" example
@deck.gl/arcgis does not show up in the "google-maps" example
@deck.gl/arcgis does not show up in the "mapbox" example
Neither does the "basic"



> `@esri/react-arcgis` locks `esri-loader` to 2.14.0. I don't know why they do it but you should probably report it to that package's maintainers.

I'm happy to bring this up to them!



> * If you remove `esri-loader` from package.json you should not see any errors. You'll end up with both versions of `esri-loader` as sub dependencies but that should be ok.

Wow, nice!

**Comment by Pessimistress** [comment]
Hmm looks like you are right about `@deck.gl/arcgis`. Thanks for fixing the example!

**Review by Pessimistress — APPROVED** [review]

**Comment by jamesEmerson112** [comment]
Always a pleasure!

**Comment by Pessimistress** [comment]
@jamesEmerson112 Did you mean to close this?

**Comment by jamesEmerson112** [comment]
@Pessimistress oh I am under the impression that once the PR is approved, the PR should be closed.

Was I not supposed to do so because `@deck.gl/arcgis` is not sorted out? I am happy to receive criticisms

**Comment by Pessimistress** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests

**Comment by jamesEmerson112** [comment]
Thank you for the clarification! I absolutely did not mean to close this!

**Pull request merged**
