### PR TITLE
[fix] set onError before setLayers

### PR DESCRIPTION
**Pull request by igorDykhta**
For #5600 

#### Change List
- Set onError before setLayers.

### CODE REVIEW

**Review by ibgreen — APPROVED** [review]
Maybe add a comment stating that this needs to be called before other things to ensure we capture all errors?

**Comment by Pessimistress** [comment]
Why is this not merged into master?

**Comment by igorDykhta** [comment]
@Pessimistress on master and 8.5.x we don't call setLayers from there anymore

**Comment by Pessimistress** [comment]
@igorDykhta you identified an issue regarding the call order of setLayers vs onError, but you reordered the settings of onError to be before other operations too. Not merging into master creates a potential behavior discrepancy between master and release branches.

**Pull request merged**
